import numpy as np
from typing import Dict, List, Any, Tuple

VIRTUAL_CAMERA_BLOCKLIST = [
    "obs",
    "v4l2loopback",
    "virtual",
    "camtwist",
    "droidcam",
    "manycam",
    "xsplit",
    "snap camera",
    "snap cam",
    "camlink",
    "streamlabs",
    "ip camera",
    "fake",
    "screen-capture"
]


class EnvironmentValidator:
    @staticmethod
    def validate_automation(data: Dict[str, Any]) -> Tuple[bool, str, Dict[str, Any]]:
        """
        Validates client automation flags.
        Returns: (passed: bool, display_status: str, details: dict)
        """
        is_webdriver = data.get("webdriver", False)
        plugins_count = data.get("plugins_length", 0)
        has_chrome_obj = data.get("has_chrome_object", True)
        user_agent = data.get("user_agent", "").lower()
        languages = data.get("languages", [])
        
        is_headless = "headless" in user_agent or "electron" in user_agent
        
        reasons = []
        if is_webdriver:
            reasons.append("navigator.webdriver is TRUE")
        if is_headless:
            reasons.append("Headless browser signature in User-Agent")
        if plugins_count == 0 and "windows" in user_agent:
            reasons.append("Zero plugins detected in Chrome desktop environment")
        if not has_chrome_obj and "chrome" in user_agent:
            reasons.append("Missing standard window.chrome bindings")
        if len(languages) == 0:
            reasons.append("Missing navigator.languages locale list")
            
        passed = len(reasons) == 0
        status_text = "PASSED" if passed else "AUTOMATION DETECTED"
        
        details = {
            "webdriver": is_webdriver,
            "plugins_count": plugins_count,
            "has_chrome_object": has_chrome_obj,
            "is_headless": is_headless,
            "reasons": reasons
        }
        return passed, status_text, details

    @staticmethod
    def validate_camera(devices: List[Dict[str, str]]) -> Tuple[bool, str, Dict[str, Any]]:
        """
        Validates camera devices against virtual camera loopbacks & multiple camera injection.
        """
        video_devices = [d for d in devices if d.get("kind") == "videoinput"]
        
        detected_virtual = []
        for dev in video_devices:
            label = dev.get("label", "").lower()
            for blocked_name in VIRTUAL_CAMERA_BLOCKLIST:
                if blocked_name in label:
                    detected_virtual.append(f"{label} (matched: {blocked_name})")
                    break
                    
        # Guard: Check for multiple cameras
        multiple_cameras = len(video_devices) > 1
        
        passed = (len(detected_virtual) == 0) and not multiple_cameras
        
        if len(detected_virtual) > 0:
            status_text = "VIRTUAL CAM BLOCKED"
        elif multiple_cameras:
            status_text = f"BLOCKED ({len(video_devices)} CAMS DETECTED)"
        else:
            first_label = video_devices[0].get("label", "Standard Hardware Camera") if video_devices else "Hardware OK"
            status_text = "HARDWARE OK"
            
        details = {
            "video_camera_count": len(video_devices),
            "virtual_cameras_detected": detected_virtual,
            "multiple_cameras_flag": multiple_cameras,
            "devices": [d.get("label", "Unknown") for d in video_devices]
        }
        return passed, status_text, details

    @staticmethod
    def validate_frame_jitter(deltas: List[float]) -> Tuple[bool, str, float, Dict[str, Any]]:
        """
        Computes inter-frame timing variance across requestVideoFrameCallback timestamps.
        Near-zero variance indicates synthetic / software-timed frame injection.
        """
        # Fail closed. env_data is sent once with a complete payload, so there is
        # no "still measuring" state here — too few samples means the pacing was
        # never verified, and an attacker can produce that state at will by
        # dropping requestVideoFrameCallback. An unverified check is not a pass.
        n = len(deltas) if deltas else 0
        if n < 15:
            reason = ("requestVideoFrameCallback unavailable — no frame pacing reported"
                      if n == 0 else f"only {n} samples, need 15")
            return False, "UNVERIFIED (NO PACING DATA)", 0.0, {
                "sample_count": n,
                "unverified": True,
                "reason": reason
            }
            
        deltas_np = np.array(deltas, dtype=np.float64)
        variance = float(np.var(deltas_np))
        mean_delta = float(np.mean(deltas_np))
        
        # Hard check: If variance is near zero (e.g. < 0.005 ms^2), frames are generated by software loop timer
        is_synthetic = variance < 0.008
        
        # Check for abnormal frame drop or extreme variance (e.g. slideshow playback)
        is_unstable = variance > 2500.0  # extreme jitter
        
        passed = (not is_synthetic) and (not is_unstable)
        
        if is_synthetic:
            status_text = f"{variance:.3f} ms² (SYNTHETIC)"
        elif is_unstable:
            status_text = f"{variance:.1f} ms² (UNSTABLE)"
        else:
            status_text = f"{variance:.2f} ms² (OK)"
            
        details = {
            "variance_ms2": round(variance, 4),
            "mean_delta_ms": round(mean_delta, 2),
            "fps_estimate": round(1000.0 / mean_delta, 1) if mean_delta > 0 else 0,
            "sample_count": len(deltas),
            "is_synthetic": is_synthetic
        }
        return passed, status_text, variance, details
